#!/usr/bin/env python3
"""Embeds the rules pages of the other games (docs/kurallar_*.md) into src/ui/RulesText.inc.

The game parses that light markdown at runtime (Screens.cpp, parseRulesMd): '## ' headings, paragraphs,
'- ' / '1. ' bullets, '**bold**' and simple '| a | b |' tables. The '# ' title and the 'Kaynaklar' section
are left out of the game (the sources stay in the docs). Run after editing a doc:  python3 tools/gen_rules.py
"""
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
games = ["tavla", "pisti", "batak", "king", "altmisalti", "dama", "bezik", "konken"]
out = ["// Generated by tools/gen_rules.py from docs/kurallar_*.md: edit the docs, then run the script.", ""]
for g in games:
    text = (root / "docs" / f"kurallar_{g}.md").read_text(encoding="utf-8")
    keep = []
    for line in text.splitlines():
        if line.startswith("# "):
            continue
        if line.startswith("## Kaynaklar"):
            break
        keep.append(line)
    body = "\n".join(keep).strip() + "\n"
    out.append(f'static const char* const kRules_{g} = R"RULES({body})RULES";')
    out.append("")
(root / "src" / "ui" / "RulesText.inc").write_text("\n".join(out), encoding="utf-8")
print("wrote src/ui/RulesText.inc")
